export const adm = {
    UN_DIA: 24 * 60 * 60 * 1000,
    TIPO_USUARIO_SUPERADMIN: 1,
    TIPO_USUARIO_ADMIN: 2,
    TIPO_USUARIO_OPERADOR: 3,
    TIPO_USUARIO_FACTURACION: 4,
    TIPO_USUARIO_ASESOR: 5,
    TIPO_USUARIO_USUARIO_CLIENTE: 6,

    NUMERO_DECIMALES:2,
    NUMERO_DECIMALES_ICE:5,
    PIPE_NUMERO_DECIMALES:'1.2-2',
    PIPE_FECHA:'dd/MM/yyyy HH:mm',
    SEGUNDOS_GPS:5,
  };
