export const sfe = {
    CODIGO_TIPO_EMISION_ONLINE: 1,
    CODIGO_TIPO_EMISION_OFFLINE: 2,
    CODIGO_TIPO_EMISION_MASIVO: 3,


    CODIGO_TIPO_DOCUMENTO_CI: 1,
    CODIGO_TIPO_DOCUMENTO_NIT: 5,


    CODIGO_TIPO_PAGO_EFECTIVO: 1,
    CODIGO_TIPO_PAGO_TARJETA: 2,
    CODIGO_TIPO_PAGO_POSTERIOR: 6,
    CODIGO_TIPO_PAGO_DEPOSITO_EN_CUENTA: 8,
    CODIGO_TIPO_PAGO_ONLINE: 33,

    CODIGO_PAIS_BOLIVIA: 22,

    CODIGO_TIPO_MONEDA_BOLIVIANO: 1,
    TIPO_DE_CAMBIO_BOLIVIANO:1,

    ESTADO_FACTURA_PENDIENTE: 901,
    ESTADO_FACTURA_RECHAZADA: 902,
    ESTADO_FACTURA_VALIDADO: 908,
    ESTADO_FACTURA_ANULADO: 905,
    ESTADO_FACTURA_OBSERVADO: 904,
    ESTADO_FACTURA_REVERTIDA: 907,

    TIPO_EVENTO_CONTIGENCIA: 7,

    CODIGO_DOCUMENTO_SECTOR_COMPRA_VENTA:1,
    CODIGO_DOCUMENTO_SECTOR_HOSPITAL_CLINICA:17,
    CODIGO_DOCUMENTO_SECTOR_ALQUILERES:2,
    CODIGO_DOCUMENTO_SECTOR_SEGUROS:34,
    CODIGO_DOCUMENTO_SECTOR_HOTELES:16,
    CODIGO_DOCUMENTO_SECTOR_SERVICIOS_TURISTICOS_HOSPEDAJE:6,
    CODIGO_DOCUMENTO_SECTOR_EDUCATIVO:11,
    CODIGO_DOCUMENTO_SECTOR_TASA_CERO:8,
    CODIGO_DOCUMENTO_SECTOR_ICE:14,
    CODIGO_DOCUMENTO_SECTOR_VENTA_MINERAL:21,
    CODIGO_DOCUMENTO_SECTOR_COMERCIALIZACION_EXPORTACION_MINERA:20,

    MENSAJE_SIN_FACTURACION_ASIGANDA: 'No tiene facturación asignada',

    TASA_EFECTIVA: 0.1494253,
  };
