export const spv = {
    ESTADO_COMPRA_PEDIDO: 14,
    ESTADO_COMPRA_RECIBIDA: 15,

    ESTADO_TRASPASO_SOLICITADO: 26,
    ESTADO_TRASPASO_FINALIZADO: 27,

    ESTADO_VENTA_PEDIDO: 16,
    ESTADO_VENTA_COBRADA: 17,
    ESTADO_VENTA_CREDITO_POR_PAGAR: 18,
    ESTADO_VENTA_CREDITO_PAGADO: 19,
    ESTADO_VENTA_REVERTIDA: 20,

    ESTADO_TURNO_ABIERTO: 32,
    ESTADO_TURNO_CERRADO: 33,

    TIPO_VENTA_CONTADO: 23,
    TIPO_VENTA_CREDITO: 24,
    TIPO_VENTA_ONLINE: 25,

    TIPO_DESCUENTO_TOTAL: 42,
    TIPO_DESCUENTO_MONTO: 44,
    TIPO_DESCUENTO_PORCENTAJE: 43,

    TIPO_PRODUCTO_SERVICIO_HOTEL_TURISMO: 11,
    TIPO_PRODUCTO_CON_INVENTARIO: 12,
    TIPO_PRODUCTO_PRODUCTO: 13,

    TIPO_HISTORIAL_ENTRADA_AJUSTE: 37,
    TIPO_HISTORIAL_SALIDA_AJUSTE: 40,
  };
